In [25]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
df = pd.read_csv("counts.csv")
print(df.shape)
print(df["feature"][0])
labels = df["feature"].to_numpy()
print(len(labels))
print(labels)
for i in range(len(labels)):
    a = df.loc[i].to_numpy()
    print(a)
    a = a[1:]
    print(a)
    a = a[a != 0]
    plt.hist(a)
    plt.xlabel('number of appearances')
    plt.ylabel('count')
    plt.title(f"Distributition of {labels[i]}")
    plt.savefig(f"distribplots/{labels[i]}.png")
    plt.clf()







(14393, 1877)
Xkr4
14393
['Xkr4' 'Mrpl15' 'Lypla1' ... 'AC168977.1' 'PISD' 'DHRSX']
['Xkr4' 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
['Mrpl15' 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
['Lypla1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Tcea1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Rgs20' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Atp6v1h' 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
['Rb1cc1' 0 0 ... 0 0 1]
[0 0 0 ... 0 0 1]
['4732440D04Rik' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['St18' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Pcmtd1' 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
['Gm26901' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Sntg1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Rrs1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Adhfe1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['3110035E14Rik' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Mybl1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Vcpip1' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Sgk3' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Mcmdc2' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Snhg6' 0 0 ... 0 2 0]
[0 0 1 ... 0 2 0]
['Ppp1r42' 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
['Cops5' 

<Figure size 432x288 with 0 Axes>